# Generated by Django 3.1.2 on 2020-10-16 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=128, verbose_name='办公区')),
                ('address', models.CharField(default='NULL', max_length=128, verbose_name='办公区地址')),
                ('contacts', models.CharField(default='NULL', max_length=128, verbose_name='联系人')),
                ('mobel', models.CharField(default='NULL', max_length=128, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '办公区',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, '在线'), (1, '离线')], default=0, max_length=128, verbose_name='设备状态')),
                ('name', models.CharField(default='NULL', max_length=128, verbose_name='设备名称')),
                ('devicerole', models.CharField(default='NULL', max_length=128, verbose_name='设备角色')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('describe', models.CharField(default='NULL', max_length=128, verbose_name='制造商')),
                ('model', models.CharField(default='NULL', max_length=128, verbose_name='设备型号')),
                ('software', models.CharField(default='NULL', max_length=128, verbose_name='软件版本')),
                ('sn', models.CharField(default='NULL', max_length=128, verbose_name='SN')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bgq', models.ForeignKey(help_text='$显示字段$__username', on_delete=django.db.models.deletion.CASCADE, to='user.bgqinfo', verbose_name='办公区')),
                ('changed_by', models.ForeignKey(blank=True, help_text='$显示字段$__username', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '设备资产',
                'verbose_name_plural': '设备资产',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNetworkDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, '在线'), (1, '离线')], default=0, max_length=128, verbose_name='设备状态')),
                ('name', models.CharField(default='NULL', max_length=128, verbose_name='设备名称')),
                ('devicerole', models.CharField(default='NULL', max_length=128, verbose_name='设备角色')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('describe', models.CharField(default='NULL', max_length=128, verbose_name='制造商')),
                ('model', models.CharField(default='NULL', max_length=128, verbose_name='设备型号')),
                ('software', models.CharField(default='NULL', max_length=128, verbose_name='软件版本')),
                ('sn', models.CharField(default='NULL', max_length=128, verbose_name='SN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bgq', models.ForeignKey(blank=True, db_constraint=False, help_text='$显示字段$__username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.bgqinfo', verbose_name='办公区')),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='$显示字段$__username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 设备资产',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AutoDiscovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_network', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='IP地址段')),
                ('bgq', models.ForeignKey(help_text='$显示字段$__name', on_delete=django.db.models.deletion.CASCADE, to='user.bgqinfo', verbose_name='办公区')),
            ],
            options={
                'verbose_name': '自动发现',
            },
        ),
    ]
