# Generated by Django 3.1.2 on 2020-10-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_autodiscovery_bgqinfo_historicalnetworkdevice_networkdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyAdminModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=500, verbose_name='模型名称')),
                ('model_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='模型备注')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='bgq',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='$显示字段$__name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.bgqinfo', verbose_name='办公区'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='bgq',
            field=models.ForeignKey(help_text='$显示字段$__name', on_delete=django.db.models.deletion.CASCADE, to='user.bgqinfo', verbose_name='办公区'),
        ),
        migrations.CreateModel(
            name='TyAdminModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=500, verbose_name='字段名')),
                ('field_type', models.CharField(max_length=500, verbose_name='字段类型')),
                ('field_help', models.TextField(max_length=500, verbose_name='字段帮助')),
                ('name', models.ForeignKey(help_text='$显示字段$__name', on_delete=django.db.models.deletion.CASCADE, to='user.tyadminmodelconfig', verbose_name='所属模型')),
            ],
        ),
    ]
