# Generated by Django 3.1.2 on 2020-10-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201016_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyadminmodelconfig',
            options={'verbose_name': '模型配置'},
        ),
        migrations.AlterModelOptions(
            name='tyadminmodelfield',
            options={'verbose_name': '字段配置'},
        ),
        migrations.RenameField(
            model_name='tyadminmodelconfig',
            old_name='model_remark',
            new_name='verbose_name',
        ),
        migrations.RenameField(
            model_name='tyadminmodelfield',
            old_name='field_help',
            new_name='help',
        ),
        migrations.RenameField(
            model_name='tyadminmodelfield',
            old_name='field_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='tyadminmodelconfig',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='tyadminmodelfield',
            name='field_name',
        ),
        migrations.AddField(
            model_name='tyadminmodelconfig',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='模型名称'),
        ),
        migrations.AddField(
            model_name='tyadminmodelfield',
            name='desc',
            field=models.CharField(default='', max_length=500, verbose_name='字段描述'),
        ),
        migrations.AddField(
            model_name='tyadminmodelfield',
            name='model_name',
            field=models.ForeignKey(blank=True, help_text='$显示字段$__name', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tyadminmodelconfig', verbose_name='所属模型'),
        ),
        migrations.AddField(
            model_name='tyadminmodelfield',
            name='require',
            field=models.BooleanField(default=True, verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='tyadminmodelfield',
            name='name',
            field=models.CharField(max_length=500, verbose_name='字段名'),
        ),
    ]
