# Generated by Django 3.1.2 on 2020-10-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201016_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyAdminMenuConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='菜单名称')),
                ('path', models.CharField(default='', max_length=500, verbose_name='菜单路径')),
                ('icon', models.CharField(default='', max_length=500, verbose_name='菜单图标')),
                ('component', models.CharField(default='', max_length=500, verbose_name='菜单对应组件')),
                ('parent_menu', models.ForeignKey(blank=True, help_text='$显示字段$__name', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tyadminmenuconfig', verbose_name='父级菜单')),
            ],
        ),
    ]
